### ISSUE TITLE
The method dispose was called on null

### ISSUE THREAD

**Issue by DevNico** [aleksanderwozniak/table_calendar#130]
If you dispose a widget with a CalendarController before the TableCalendar widget was built.

e.g. The Application has a bottomappbar and on page one is a table calendar which is built after some data is loaded from the web but the user switches to the second page before that happens. Resulting in an error.

Error message:
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown while finalizing the widget tree:
flutter: The method 'dispose' was called on null.
flutter: Receiver: null
flutter: Tried calling: dispose()
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
flutter: #1      CalendarController.dispose (package:table_calendar/src/calendar_controller.dart:143:21)
flutter: #2      _DashboardPageState.dispose (package:test_app/views/dashboard.dart:30:58)
flutter: #3      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4135:12)
flutter: #4      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1738:13)
flutter: #5      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
flutter: #6      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1747:25)
flutter: #7      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2428:27)
flutter: #8      BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2259:15)
flutter: #9      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2427:7)
flutter: #10     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:777:18)
flutter: #11     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:279:5)
flutter: #12     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1040:15)
flutter: #13     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:982:9)
flutter: #14     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:898:5)
flutter: #18     _invoke (dart:ui/hooks.dart:251:10)
flutter: #19     _drawFrame (dart:ui/hooks.dart:209:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by vertigeaux** [comment]
Same issue here with calendar in TabBarView. If the tab is loaded and calendar is built, no error. If the tabbed screen is navigated away from without building calendar, controller is null and dispose() throws exception.

Checking if controller is null before calling dispose() does not help.

**Comment by aleksanderwozniak** [comment]
Can you check if the fix from `dev` branch solves your issue?

Replace your current `pubspec.yaml` entry with this:
```yaml
table_calendar:
  git:
    url: git://github.com/aleksanderwozniak/table_calendar.git
    ref: dev
```

Then update packages and reload your code.

**Comment by vertigeaux** [comment]
This issue seems resolved in dev branch for me. 

Tip for OP: the events property has moved from TableCalendar to the controller.

**Comment by aleksanderwozniak** [comment]
@DevNico 
The reason was to allow dynamic data updates (#86 ). I wasn't quite satisfied with solution, hence `dev` branch is not merged yet. It should happen in a few days tho.

Follow #133 to be up to date.
