### ISSUE TITLE
Swiping through pages causes exception

### ISSUE THREAD

**Issue by spareblock** [aleksanderwozniak/table_calendar#305]
So I'm using the beta version using the PageView.
I haven't noticed this problem when I was swiping through pages but now that I created two buttons to navigate back and forward through pages and I started getting this exception. I'm guessing maybe because it's too fast? Although, it's not that fast and within reasonable tapping speed.

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/sliver_fixed_extent_list.dart': Failed assertion: line 278 pos 12:
flutter: 'firstIndex == 0 || childScrollOffset(firstChild) - scrollOffset <= precisionErrorTolerance': is not
flutter: true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   PageView
flutter:   file:///Users/x/Library/Flutter/.pub-cache/git/table_calendar-0fb806a111d87a42a60745ffb463499e9d74a904/lib/src/calendar.dart:365:29
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:278:12)
flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #4      RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:11)
flutter: #5      _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:170:11)
flutter: #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1769:7)
flutter: #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:471:13)
flutter: #8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1465:12)
flutter: #9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1374:20)
flutter: #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1632:7)
flutter: #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:889:18)
flutter: #12     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:404:19)
flutter: #13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:867:13)
flutter: #14     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #15     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
flutter: #16     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1056:9)
flutter: #17     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:972:5)
flutter: #21     _invoke (dart:ui/hooks.dart:253:10)
flutter: #22     _drawFrame (dart:ui/hooks.dart:211:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderSliverFillViewport#a5858 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: _SliverFillViewportRenderObjectWidget ← _SliverFractionalPadding ← SliverFillViewport ←
flutter:     Viewport ← IgnorePointer-[GlobalKey#f8e20] ← Semantics ← _PointerListener ← Listener ←
flutter:     _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#72064] ←
flutter:     _PointerListener ← Listener ← ⋯
flutter:   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: SliverConstraints(AxisDirection.right, GrowthDirection.forward, ScrollDirection.idle,
flutter:     scrollOffset: 3981194.0, remainingPaintExtent: 398.0, crossAxisExtent: 76.0, crossAxisDirection:
flutter:     AxisDirection.down, viewportMainAxisExtent: 398.0, remainingCacheExtent: 398.0, cacheOrigin: 0.0)
flutter:   geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 398.0, maxPaintExtent: Infinity,
flutter:     hasVisualOverflow: true, cacheExtent: 398.0)
flutter:   currently live children: 10003 to 10003
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child with index 10003: RenderIndexedSemantics#a6c54
flutter:       child: RenderSemanticsGestureHandler#da45c
flutter:         child: RenderPointerListener#ffec9
flutter:           child: RenderTable#a8a64
flutter:             child (0, 0): RenderPositionedBox#eda50 relayoutBoundary=up1
flutter:             child (1, 0): RenderPositionedBox#5dada relayoutBoundary=up1
flutter:             child (2, 0): RenderPositionedBox#3995c relayoutBoundary=up1
flutter:             child (3, 0): RenderPositionedBox#c03a8 relayoutBoundary=up1
flutter:             child (4, 0): RenderPositionedBox#8400b relayoutBoundary=up1
flutter:             child (5, 0): RenderPositionedBox#a1115 relayoutBoundary=up1
flutter:             child (6, 0): RenderPositionedBox#254e9 relayoutBoundary=up1
flutter:             child (0, 1): RenderConstrainedBox#f267e relayoutBoundary=up1
flutter:             child (1, 1): RenderConstrainedBox#af40f relayoutBoundary=up1
flutter:             child (2, 1): RenderConstrainedBox#33fef relayoutBoundary=up1
flutter:             child (3, 1): RenderConstrainedBox#83721 relayoutBoundary=up1
flutter:             child (4, 1): RenderConstrainedBox#98c61 relayoutBoundary=up1
flutter:             child (5, 1): RenderConstrainedBox#80817 relayoutBoundary=up1
flutter:             child (6, 1): RenderConstrainedBox#2e242 relayoutBoundary=up1
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by aleksanderwozniak** [comment]
Hi, can you please provide a self-contained example, so that I can recreate the issue on my end?
