### ISSUE TITLE
Cannot set value in unmodifiable Map

### ISSUE THREAD

**Issue by erperejildo** [aleksanderwozniak/table_calendar#485]
Since I was getting `Field '_events@130342178' has not been initialized` I had to add this:
`initializeDateFormatting().then((_) => runApp(MyApp()));`

But then I got this:
```
======== Exception caught by widgets library =======================================================
The following UnsupportedError was thrown building MediaQuery(MediaQueryData(size: Size(392.7, 759.3), devicePixelRatio: 2.8, textScaleFactor: 1.0, platformBrightness: Brightness.light, padding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewPadding: EdgeInsets(0.0, 24.0, 0.0, 0.0), viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false, accessibleNavigation: false, highContrast: false, disableAnimations: false, invertColors: false, boldText: false, navigationMode: traditional)):
Unsupported operation: Cannot set value in unmodifiable Map

The relevant error-causing widget was: 
  MaterialApp file:///Users/dani/repos/dani/my_rents/lib/main.dart:92:14
When the exception was thrown, this was the stack: 
#0      _ImmutableMap.[]= (dart:core-patch/immutable_map.dart:74:5)
#1      initializeDateFormattingCustom (package:intl/date_symbol_data_custom.dart:35:19)
#2      loadDateIntlDataIfNotLoaded.<anonymous closure> (package:flutter_localizations/src/utils/date_localizations.dart:44:9)
#3      CastMap.forEach.<anonymous closure> (dart:_internal/cast.dart:288:8)
#4      _ImmutableMap.forEach (dart:core-patch/immutable_map.dart:43:8)
```

I checked this issue https://github.com/aleksanderwozniak/table_calendar/issues/454 and the other one linked but I didn't find any solution

```
initializeDateFormatting().then(
    (_) => runApp(
      LocalizedApp(
        delegate,
        MyApp(
          localizedValues: {},
        ),
      ),
    ),
  );
```

https://github.com/aissat/easy_localization/issues/215#issuecomment-652559642

**Comment by aleksanderwozniak** [comment]
> 
> 
> Since I was getting `Field '_events@130342178' has not been initialized` I had to add this:
> `initializeDateFormatting().then((_) => runApp(MyApp()));`

This doesn't seem to be related to date formatting or locale. Aren't you missing a constructor for `_events`?

**Comment by erperejildo** [comment]
Not sure, this is my tableCalendar:
```
TableCalendar<CalendarEvent>(
          // locale: Provider.of<MyRents>(context).language,
          // availableCalendarFormats: {
          //   CalendarFormat.month: translate('calendar.month'),
          //   CalendarFormat.week: translate('calendar.week'),
          //   CalendarFormat.twoWeeks: translate('calendar.two_weeks'),
          // },
          availableGestures: AvailableGestures.horizontalSwipe,
          calendarBuilders: CalendarBuilders(
            singleMarkerBuilder: (context, date, event) {
              return Container(
                height: 8.0,
                width: 8.0,
                margin: const EdgeInsets.all(0.5),
                decoration: BoxDecoration(
                  color: Color(
                    int.parse(
                      event.color.replaceFirst('#', '0xFF'),
                    ),
                  ), // TODO: change
                  // color: Helpers.hexToColor(event["color"]),
                  shape: BoxShape.circle,
                ),
              );
            },
          ),
          headerStyle: HeaderStyle(
            formatButtonDecoration: BoxDecoration(
              color: Colors.blue,
              borderRadius: BorderRadius.circular(20.0),
            ),
            formatButtonTextStyle: TextStyle(
              color: Colors.white,
            ),
          ),
          calendarStyle: CalendarStyle(
            // texts color
            // todayTextStyle: TextStyle(colo: Colors.grey.withOpacity(0.7)),
            // selectedTextStyle: TextStyle(color: Colors.blue.withOpacity(0.7)),
            todayDecoration: BoxDecoration(
              color: Colors.grey.withOpacity(0.7),
              shape: BoxShape.circle,
            ),
            selectedDecoration: BoxDecoration(
              color: Colors.blue[400],
              shape: BoxShape.circle,
            ),
          ),
          onDaySelected: _onDaySelected,
          startingDayOfWeek: StartingDayOfWeek.monday,
          // initialCalendarFormat: CalendarFormat.month,
          // calendarController: this._calendarController,
          firstDay: kFirstDay,
          lastDay: kLastDay,
          focusedDay: _focusedDay!,
          selectedDayPredicate: (day) => isSameDay(_selectedDay, day),
          calendarFormat: _calendarFormat,
          eventLoader: _getEventsForDay,
          onFormatChanged: (format) {
            if (_calendarFormat != format) {
              setState(() {
                _calendarFormat = format;
              });
            }
          },
          onPageChanged: (focusedDay) {
            _focusedDay = focusedDay;
          },
        ),
```

**Comment by erperejildo** [comment]
Found it. I was missing this part before creating the event:
```
if (kEvents[_selectedDay] == null) {
     kEvents[_selectedDay!] = [];
}
```
