### ISSUE TITLE
Programmatically tap or simulate tap on a table calendar cell

### ISSUE THREAD

**Issue by MysticFragilist** [aleksanderwozniak/table_calendar#505]
Hi,

First of, thanks for your library it has been proven really useful. Currently, I change the version from 2.1.X to 3.0.0 and everything worked well after some tweaking (like you mentionned, I remove CalendarController and modify the predicate functions accordingly). Now the UI is working as previously and that's good. The only thing, is that before, I had a test which was tapping on a cell as such: 
```dart
//pump the widget and wait for it to load correctly on screen
await tester.pumpWidget(localizedWidget(
    child: MediaQuery(
        data: const MediaQueryData(textScaleFactor: 0.5),
        child: ScheduleView(initialDay: DateTime(2020, 2, 15)))));
await tester.pumpAndSettle();

// [...]

// Tap on the day after selected day
await tester.tap(find.descendant(
    of: find.byType(TableCalendar, skipOffstage: false),
    matching: find.text(
        "${DateTime(2020, 2, 15).add(const Duration(days: 1)).day}")));
```
this test doesn't pass anymore it says that the widget with text "16" is not present on screen when it is clearly loaded:
```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with text "16" that has ancestor(s) with type "TableCalendar<dynamic>"
(ignoring offstage widgets)" (used in a call to "tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:897:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:836:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:271:18)
#3      main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///home/samuelmo/Documents/Notre-Dame/test/ui/views/schedule_view_test.dart:229:22)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

With the new version I guess my question is, how can I achieve the same outcome as before and/or is there a change in how the cell are process?

**Comment by aleksanderwozniak** [comment]
Hi Samuel,

- Do you have any other exceptions when running this particular test?
- Do you use typed events with your TableCalendar widget?

**Comment by MysticFragilist** [comment]
Thanks for the quick answer!

* No, that's the only exception I get from it, I even have some  expect test call that are done before that worked well.
* I'm not sure if it's what you meant, but I do build Events marker on the calendar using some customised widget:
```dart
Widget _buildEventsMarker(
      ScheduleViewModel model, DateTime date, List events) {
    if (events.isNotEmpty) {
      return Positioned(
        right: 1,
        bottom: 1,
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 200),
          decoration: BoxDecoration(
            color: isSameDay(date, model.selectedDate)
                ? _selectedColor
                : _defaultColor,
          ),
          width: 16.0,
          height: 16.0,
          child: Center(
            child: Text(
              '${events.length}',
              style: const TextStyle().copyWith(
                color: Colors.white,
                fontSize: 12.0,
              ),
            ),
          ),
        ),
      );
    }
    return null;
  }
```
Which is then called into my `_buildTableCalendar`:
```dart
 Widget _buildTableCalendar(ScheduleViewModel model) => TableCalendar(
        startingDayOfWeek:
            model.settings[PreferencesFlag.scheduleSettingsStartWeekday]
                as StartingDayOfWeek,
        locale: model.locale.toLanguageTag(),
        selectedDayPredicate: (day) {
          return isSameDay(model.selectedDate, day);
        },
        weekendDays: const [],
        headerStyle:
            const HeaderStyle(titleCentered: true, formatButtonVisible: false),
        eventLoader: model.coursesActivitiesFor,
        onDaySelected: (selectedDay, focusedDay) {
          setState(() {
            model.selectedDate = selectedDay;
            model.focusedDate = focusedDay;
          });
        },
        calendarFormat: model.calendarFormat,
        onFormatChanged: (format) {
          setState(() {
            model.setCalendarFormat(format);
          });
        },
        focusedDay: model.focusedDate,
        onPageChanged: (focusedDay) {
          model.focusedDate = focusedDay;
        },
        calendarBuilders: CalendarBuilders(
            todayBuilder: (context, date, _) =>
                _buildSelectedDate(date, _defaultColor),
            selectedBuilder: (context, date, _) => FadeTransition(
                  opacity:
                      Tween(begin: 0.0, end: 1.0).animate(_animationController),
                  child: _buildSelectedDate(date, _selectedColor),
                ),
            markerBuilder: (context, date, events) =>
                _buildEventsMarker(model, date, events)), // ====== The events are build here! ======
        firstDay: DateTime.utc(2010, 12, 31),
        lastDay: DateTime.utc(2100, 12, 31),
      );
```

**Comment by MysticFragilist** [comment]
After investigation, this was an error from our side. It seems that the focused day wasn't set with the initial day as the selectedDay was in our model.
Sorry to have bother you and keep up the good work! 😄
