### ISSUE TITLE
NoSuchMethodError: The method 'take' was called on null.

### ISSUE THREAD

**Issue by benoitverstraete** [aleksanderwozniak/table_calendar#53]
Hi @aleksanderwozniak ,

I tested your example code at [https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart) and there is an exception thrown when you slide the calendar to the left (april 2019).

Here is the callstack :

```
I/flutter ( 4870): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4870): The following NoSuchMethodError was thrown building LayoutBuilder:
I/flutter ( 4870): The method 'take' was called on null.
I/flutter ( 4870): Receiver: null
I/flutter ( 4870): Tried calling: take(4)
I/flutter ( 4870): 
I/flutter ( 4870): When the exception was thrown, this was the stack:
I/flutter ( 4870): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 4870): #1      _TableCalendarState._buildCell (package:table_calendar/table_calendar.dart:500:46)
I/flutter ( 4870): #2      _TableCalendarState._buildTableCell.<anonymous closure> (package:table_calendar/table_calendar.dart:480:20)
I/flutter ( 4870): #3      _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:113:26)
I/flutter ( 4870): #4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2294:19)
I/flutter ( 4870): #5      _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:109:11)
I/flutter ( 4870): #6      RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1716:58)
I/flutter ( 4870): #7      PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
I/flutter ( 4870): #8      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1716:13)
I/flutter ( 4870): #9      _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:207:5)
I/flutter ( 4870): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #11     RenderTable.performLayout (package:flutter/src/rendering/table.dart:1060:21)
I/flutter ( 4870): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4870): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4870): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4870): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4870): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4870): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4870): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #25     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 4870): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #27     RenderAnimatedSize.performLayout (package:flutter/src/rendering/animated_size.dart:182:11)
I/flutter ( 4870): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #29     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter ( 4870): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4870): #32     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 4870): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #34     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter ( 4870): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
I/flutter ( 4870): #36     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 4870): #37     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 4870): #38     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 4870): #39     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 4870): #40     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1497:7)
I/flutter ( 4870): #41     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 4870): #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 4870): #43     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 4870): #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 4870): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 4870): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 4870): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 4870): #51     _invoke (dart:ui/hooks.dart:220:10)
I/flutter ( 4870): #52     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 4870): (elided 3 frames from package dart:async)
```

Best regards

**Comment by aleksanderwozniak** [comment]
Thanks for the report!

Fixed with #57
