### ISSUE TITLE
Bug: _TableCalendarBaseState.didUpdateWidget might throw AssertionError

### ISSUE THREAD

**Issue by MichaelTamm** [aleksanderwozniak/table_calendar#651]
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Flexible(flex: 0):
ScrollController not attached to any scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 107 pos 12: '_positions.isNotEmpty'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was:
  Flexible
  Flexible:file:///home/Michael/.pub-cache/hosted/pub.dartlang.org/table_calendar-3.0.3/lib/src/table_calendar.dart:475:9

When the exception was thrown, this was the stack:
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:107:12)
#3      PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:213:41)
#4      _TableCalendarBaseState._updatePage (package:table_calendar/src/table_calendar_base.dart:161:25)
#5      _TableCalendarBaseState.didUpdateWidget (package:table_calendar/src/table_calendar_base.dart:116:7)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4778:57)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3370:15)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4613:16)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:4311:5)
...
```

**Comment by MichaelTamm** [comment]
I have setup a small Flutter app, which demonstrates the bug: https://github.com/MichaelTamm/table_calendar_issue_651_demo/blob/master/lib/main.dart
