### ISSUE TITLE
Pinned weekly view within a SliverList

### ISSUE THREAD

**Issue by henk-lim** [aleksanderwozniak/table_calendar#706]
**Is your feature request related to a problem? Please describe.**
I'm not able to find a way to include the TableCalendar view to be part of a sliver list where the calendar can be pinned between its weekly and monthly view. The default vertical swipe behaviour of the calendar to change the format is contained within the calendar view itself. That is, if I have a list of events below the calendar view, I cannot swipe the entire list up to change the format of the calendar. To change the format, my finger will need to be on the calendar first. Having been used to many calendar apps out on the market to date, this seems like a standard user experience, so it feels weird now to not be able to hide the calendar with a swipe up gesture from anywhere on the screen.

**Describe the solution you'd like**
Is there a possibility to include a SliverAdapter of sort that can detect the scrolling of a sliver list to change the format of the calendar?

**Describe alternatives you've considered**
I haven't found an alternative. I'm open to any suggestions for a workaround if there is any. Thanks!

**Additional context**

**Comment by aleksanderwozniak** [comment]
Try this:

Once you detect the upward scrolling of a silver list, update `calendarFormat` variable to `CalendarFormat.week` and rebuild the `TableCalendar` widget. Same for downward scrolling, but use `CalendarFormat.month`.

**Comment by lhengl** [comment]
Hi @aleksanderwozniak 

I tried your suggestion. It is working somewhat, but it is causing the dreaded "markNeedsBuild" Exception any time the calendar changes format any time the scroll position is not at the start position. I thought it could be to do with the scrolling that is causing it, so I tried to wait for the end of the scroll. But the issue seem to be there as long as the scroll position is in the middle.

Visually this seems to work, but it always throw an Exception in the log.

Since you have helped me along this path, would you be able to give me some ideas as to what to look for?

Here's my code:

```
  Widget build(BuildContext context) {
    return controller.obx(
      (state) {
        log().d('build Scaffold');
        return Scaffold(
          appBar: _buildAppBar(),
          drawer: TaskDrawer(),
          body: Column(
            children: [
              _buildCalendar(),
              Expanded(child: _buildList()),
            ],
          ),
          floatingActionButton: _buildFab(),
        );
      },
      onLoading: LoadingPage(),
      onEmpty: EmptyPage(),
      onError: (e) => ErrorPage(message: e),
    );
  }


  Widget _buildList() {
    log().d('_buildList');
    return NotificationListener<ScrollNotification>(
      onNotification: (notification) {
        if (notification is UserScrollNotification) {
          if (notification.direction == ScrollDirection.forward) {
            log().d("_buildList : scrolling down");
            controller.isScrollingDown = true;
          } else if (notification.direction == ScrollDirection.reverse) {
            log().d("_buildList : scrolling up");
            controller.isScrollingUp = true;
          }
        }

        if (notification is ScrollEndNotification) {
          if (controller.isScrollingDown) {
            log().d("_buildList : scrolling down ended with format=${controller.format.value.name}, position=${notification.metrics.pixels}");
            if (controller.format.value != CalendarFormat.month && notification.metrics.pixels == 0) {
              controller.format.value = CalendarFormat.month;
            }
            controller.isScrollingDown = false;
          } else if (controller.isScrollingUp) {
            log().d("_buildList : scrolling up ended with format=${controller.format.value.name}, position=${notification.metrics.pixels}");
            if (controller.format.value != CalendarFormat.week && notification.metrics.pixels != 0) {
              controller.format.value = CalendarFormat.week;
            }
            controller.isScrollingUp = false;
          }
        }
        return true;
      },
      child: Obx(() {
        log().d('_buildList : CustomScrollView');
        return CustomScrollView(
          // To mitigate janky top insertion animation, the cache extent
          // must be large enough to animate the insertion even if the inserted
          // item is offscreen. See issue FIT-615
          cacheExtent: 9999,
          physics: const AlwaysScrollableScrollPhysics(),
          slivers: [
            AnimatedSliverTaskGroup(
              title: 'PENDING',
              // ignore: invalid_use_of_protected_member
              list: controller.pendingTasks.value,
              controller: controller.pendingController,
              onDone: controller.handleCheck,
            ),
            AnimatedSliverTaskGroup(
              title: 'COMPLETED',
              // ignore: invalid_use_of_protected_member
              list: controller.completedTasks.value,
              controller: controller.completedController,
              onUnDone: controller.handleUncheck,
            ),
            SliverToBoxAdapter(child: SizedBox(height: Get.mediaQuery.size.height * 0.2)),
          ],
        );
      }),
    );
  }

  Widget _buildCalendar() {
    log().d('_buildCalendar:');
    return Column(
      children: [
        WeekHeader(height: calendarHeaderHeight, textStyle: Get.textTheme.overline),
        Obx(() {
          log().d('_buildCalendar: TableCalendar');
          return TableCalendar(
            key: controller.calendarKey,
            calendarStyle: CalendarStyle(
              markerDecoration: BoxDecoration(
                color: Colors.black45,
                shape: BoxShape.circle,
              ),
            ),
            rangeStartDay: controller.selectedDate.value.asDateTime,
            focusedDay: controller.selectedDate.value.asDateTime,
            rangeSelectionMode: RangeSelectionMode.disabled,
            rowHeight: calendarRowHeight,
            sixWeekMonthsEnforced: true,
            onPageChanged: controller.handleCalendarPageChanged,
            onDaySelected: controller.handleCalendarDayTap,
            selectedDayPredicate: controller.selectedDayPredicate,
            calendarFormat: controller.format.value,
            onFormatChanged: (format) {
              log().d('Format changed');
              controller.format.value = format;
            },
            availableCalendarFormats: {
              CalendarFormat.month: CalendarFormat.month.name,
              CalendarFormat.week: CalendarFormat.week.name,
            },
            // availableGestures: AvailableGestures.horizontalSwipe,
            startingDayOfWeek: StartingDayOfWeek.monday,
            firstDay: Date.startOfTime.asDateTime,
            lastDay: Date.endOfTime.asDateTime,
            eventLoader: controller.eventLoader,
            headerVisible: false,
            daysOfWeekVisible: false,
          );
        }),
      ],
    );
  }
```

and the error:

[log] setState() or markNeedsBuild() called during build.
This AppBar widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  AppBar
The widget which was currently being built when the offending call was made was:
  Flexible
      #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4549:11)
      #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4564:6)
      #2      State.setState (package:flutter/src/widgets/framework.dart:1134:15)
      #3      _AppBarState._handleScrollNotification (package:flutter/src/material/app_bar.dart:853:9)
      #4      ScrollNotificationObserverState._notifyListeners (package:flutter/src/widgets/scroll_notification_observer.dart:135:25)
      #5      ScrollNotificationObserverState.build.<anonymous closure> (package:flutter/src/widgets/scroll_notification_observer.dart:171:11)
      #6      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
      #7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3094:18)
      #8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
      #9      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
      #10     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
      #11     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3097:13)
      #12     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4441:24)
      #13     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
      #14     ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:92:92)
      #15     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:914:15)
      #16     ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:199:7)
      #17     PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:220:14)
      #18     _TableCalendarBaseState._updatePage (package:table_calendar/src/table_calendar_base.dart:175:23)
      #19     _TableCalendarBaseState.didUpdateWidget (package:table_calendar/src/table_calendar_base.dart:121:7)
      #20     StatefulElement.update (package:flutter/src/widgets/framework.dart:5065:57)
      #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
      #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
      #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
      #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
      #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
      #26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5904:32)
      #27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
      #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
      #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
      #30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
      #31     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
      #32     StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
      #33     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
      #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
      #35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
      #36     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
      #37     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
      #38     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
      #39     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
      #40     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
      #41     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
      #42     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
      #43     _rootRun (dart:async/zone.dart:1391:13)
      #44     _CustomZone.run (dart:async/zone.dart:1293:19)
      #45     _CustomZone.runGuarded (dart:async/zone.dart:1201:7)
      #46     _invoke (dart:ui/hooks.dart:150:10)
      #47     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
      #48     _drawFrame (dart:ui/hooks.dart:115:31)

**Comment by shichunlei** [comment]
Have you solved this problem yet? I also encountered the same problem



```
======== Exception caught by widget library ========================================================
The following assertion was thrown while dispatching notifications for ScrollNotificationObserverState:
setState() or markNeedsBuild() called during build.

This AppBar widget cannot be marked as needing to build because the framework is already in the process of building widgets. A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: AppBar
  dependencies: [MediaQuery, _InheritedTheme, _LocalizationsScope-[GlobalKey#e2d94], _ModalScopeStatus, _ScrollNotificationObserverScope]
  state: _AppBarState#8dc1c
The widget which was currently being built when the offending call was made was: Flexible
  flex: 0
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4634:9)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4646:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1153:15)
#3      _AppBarState._handleScrollNotification (package:flutter/src/material/app_bar.dart:865:9)
#4      ScrollNotificationObserverState._notifyListeners (package:flutter/src/widgets/scroll_notification_observer.dart:189:25)
#5      ScrollNotificationObserverState.build.<anonymous closure> (package:flutter/src/widgets/scroll_notification_observer.dart:225:11)
#6      _NotificationElement.onNotification (package:flutter/src/widgets/notification_listener.dart:130:38)
#7      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3170:18)
#8      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#9      _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#10     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#11     _NotificationNode.dispatchNotification (package:flutter/src/widgets/framework.dart:3173:13)
#12     Element.dispatchNotification (package:flutter/src/widgets/framework.dart:4534:24)
#13     Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:60:13)
#14     ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:92:92)
#15     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:912:15)
#16     ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:204:7)
#17     PageController.jumpToPage (package:flutter/src/widgets/page_view.dart:220:14)
#18     _TableCalendarBaseState._updatePage (package:table_calendar/src/table_calendar_base.dart:157:25)
#19     _TableCalendarBaseState.didUpdateWidget (package:table_calendar/src/table_calendar_base.dart:118:7)
#20     StatefulElement.update (package:flutter/src/widgets/framework.dart:5142:55)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#24     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#26     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981:32)
#27     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#30     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#31     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#32     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#34     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981:32)
#35     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#37     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981:32)
#38     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#43     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#44     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#45     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#47     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#49     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#55     ProxyElement.update (package:flutter/src/widgets/framework.dart:5301:5)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#61     StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6384:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#66     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#67     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#68     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#69     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#71     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133:11)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#73     StatefulElement.update (package:flutter/src/widgets/framework.dart:5156:5)
#74     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#76     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#77     StatelessElement.update (package:flutter/src/widgets/framework.dart:5044:5)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#79     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5981:32)
#80     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6537:17)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3660:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993:16)
#83     Element.rebuild (package:flutter/src/widgets/framework.dart:4690:5)
#84     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2743:19)
#85     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:863:21)
#86     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#87     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#88     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#89     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#93     _invoke (dart:ui/hooks.dart:147:10)
#94     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#95     _drawFrame (dart:ui/hooks.dart:112:31)
(elided 3 frames from dart:async)
The ScrollNotificationObserverState sending notification was: ScrollNotificationObserverState#e98a1
====================================================================================================
```
